### ISSUE TITLE
Home, Features, DB Schema

### ISSUE THREAD

**Issue by paulobocanegra** [shanenak/kitchen-riffs#1]
# Wiki Page Home
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a description sentence of the app
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page
---
# Feature List
- [x] Should have 7 Features.
    - [x] 3 of those are User Auth, Live Hosting on Render, and Production README.
    - [x] The other 4 are from the [Feature List](https://open.appacademy.io/learn/swe-campus-hybrid/full-stack-project/Feature-checklist) or they have clarified them with you
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each Feature
- [x] Correctly formatted
    - [x] Features are listed in an ordered list
    - [x] Each Feature is broken down into bullet points
---
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details (primary and foreign keys, not null, indexed, unique)
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] table names, column names, and foreign keys are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded

**Comment by paulobocanegra** [comment]
**Feature List**

Formatting: 
 - Use "##" or "###" to use h2s or h3s for each feature.
 
 Features:
- Let's turn number 3 into 2 different features because notes will be like comments
----> Recipes
         - Guests can see all recipes
         - Logged in users can save recipes
         - etc..
----> Notes
         - Guests can see notes
         - Logged in users can create notes
         - Logged in users can edit and delete notes
         - etc..
 With this you will have 7 including the Readme, we can put Search as an additional feature below. You will for sure have time to finish that one as well.

**Comment by shanenak** [comment]
Thanks for reviewing Paulo! That's helpful feedback. I moved some stuff around. I agree that the saved recipes should be split up, and then I realized that I left "Home page" as an ambiguous feature, so merged Search into that (as well as formatting and other splashpage requirements). 
Let me know if you have any thoughts on my schema. I don't love that I'm listing ingredientsId in an array within each Recipe, but I know I need to maintain the order somehow.

**Comment by paulobocanegra** [comment]
You are welcome! 😄 
Features look great!

About your ingredients for a recipes:
We don't need to make ingredients their own table, each recipe can have the ingredients as part of itself.
We have a couple of options, I'll let you decide which one to use:

Option 1:
We make an array of strings. In postgress, if we want an array, we have to specify the datatype of the elements. The migration would look like:   `t.string :ingredients, array: true, null: false`

Option 2:
We make ingredients just be text, a string where we comma separate the ingredients, then we can do a recipe.ingredients.split(",") to make the array.

Option 2 is the easiest, but Option 1 may be useful if any ingredients were to have a comma.

**Comment by shanenak** [comment]
Thanks Paulo! Per our conversation last week, I'll go ahead with the ingredients table. I think I'll be able to preprocess the data in Python to minimize complexity.
