### ISSUE TITLE
Sample State, Backend & Frontend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [shanenak/kitchen-riffs#2]
# Sample State
- [x] State shape is flat!
- [x] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + The author username and imageurl for a post. Basically any info that the user can’t change
        + Like count and a boolean on whether the user likes the post instead of a likes slice
---
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show
---
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by paulobocanegra** [comment]
Backend Routes.
We don't need backend routes for getting ratings, they are associated data that we can add to the response of the associated instance on the jbuilder view. 

For example, if we get a recipe, we'll add all ratings to the response and send it to the client. If we get a user (session/show) we'll add all of that user's ratings if we want to display on the user dashboard. 

We do want to keep the PATCH & DELETE routes.

**Comment by paulobocanegra** [comment]
Frontend Routes:
`/recipes/:recipeId`
- We won't render the RecipeIndexItem here, that will be at the Index ("/" or "/search")
- We want to render RecipeShow

`/savedrecipes/:SavedRecipeId`
- Our wildcards will be camelCase, this one is just a typo.

Everything else looks great! Excellent work 💯

**Comment by shanenak** [comment]
Thank you for the feedback! That makes sense with the association. I've updated the backend and frontend routes.
